#------------------------
# Project Version
#------------------------

# Retrieve version from header file
set(PSM_VERSION_HEADER_FILE "${ROOT_DIR}/src/psmoveprotocol/ProtocolVersion.h")

file(STRINGS ${PSM_VERSION_HEADER_FILE} PSM_VERSION_PARTS
  REGEX "^#define[ \t]+PSM_RELEASE_VERSION_(MAJOR|MINOR|BUILD|REVISION)[ \t]+[0-9]+$")
  
# Verify version parts
string(REGEX MATCH "PSM_RELEASE_VERSION_MAJOR[ \t]+[0-9]+" PSM_VERSION_MAJOR ${PSM_VERSION_PARTS})
string(REGEX MATCH "PSM_RELEASE_VERSION_MINOR[ \t]+[0-9]+" PSM_VERSION_MINOR ${PSM_VERSION_PARTS})
string(REGEX MATCH "PSM_RELEASE_VERSION_BUILD[ \t]+[0-9]+" PSM_VERSION_BUILD ${PSM_VERSION_PARTS})
string(REGEX MATCH "PSM_RELEASE_VERSION_REVISION[ \t]+[0-9]+" PSM_VERSION_REVISION ${PSM_VERSION_PARTS})

if(NOT PSM_VERSION_MAJOR
    OR NOT PSM_VERSION_MINOR
    OR NOT PSM_VERSION_BUILD
    OR NOT PSM_VERSION_REVISION)
  message(FATAL_ERROR "Unable to retrieve project version from ${PSM_VERSION_HEADER_FILE}")
endif()

# Extract version numbers
string(REGEX REPLACE "PSM_RELEASE_VERSION_MAJOR[ \t]+([0-9]+)" "\\1" PSM_VERSION_MAJOR ${PSM_VERSION_MAJOR})
string(REGEX REPLACE "PSM_RELEASE_VERSION_MINOR[ \t]+([0-9]+)" "\\1" PSM_VERSION_MINOR ${PSM_VERSION_MINOR})
string(REGEX REPLACE "PSM_RELEASE_VERSION_BUILD[ \t]+([0-9]+)" "\\1" PSM_VERSION_BUILD ${PSM_VERSION_BUILD})
string(REGEX REPLACE "PSM_RELEASE_VERSION_REVISION[ \t]+([0-9]+)" "\\1" PSM_VERSION_REVISION ${PSM_VERSION_REVISION})

set(PSM_VERSION_STRING "${PSM_VERSION_MAJOR}.${PSM_VERSION_MINOR}.${PSM_VERSION_BUILD}.${PSM_VERSION_REVISION}")

message(STATUS "Project version: ${PSM_VERSION_STRING}")
